export default strings = {
    watch: "Watch",
    search: "TV shows, movies and more",
    tickets: "Get Tickets",
    trailer: "Watch Trailer",
    theaters: "In Theaters",
    genres: "Genres",
    overiew: "Overiew",
    noMovie: "No movie found",
    results: "Results Found",
    select: "Select Seats",
    from: "From",
    or: "or",
    bonus: "bonus",
    currency: "$",
    date: "Date",
    selectSeat: "Please select a hall",
    pay: "Proceed to pay",
    price: "Total price",
    rows: "row",
    selected: "Selected",
    vip: "VIP",
    regular: "Regular",
    screen: "SCREEN",
    accept: "Accept",
    reject: "Reject",
    confirm: "Confirm",
}